# Generated by Django 5.0.3 on 2024-05-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='score',
            new_name='subject_score',
        ),
    ]
