# Generated by Django 5.0.3 on 2024-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_correctanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
