# Generated by Django 5.0.3 on 2024-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_summary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
